import { StyleSheet } from "react-native";

// Card styles for dropdowns
export const cardStyles = StyleSheet.create({
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  dropdownIcon: {
    marginLeft: 8,
    color: "#002F6C",
    fontSize: 16,
    fontWeight: "bold",
  },
  dropdown: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#002F6C",
    zIndex: 1000,
    elevation: 5,
    marginTop: 5,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  dropdownItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  selectedItem: {
    backgroundColor: "#F0F8FF",
  },
  dropdownItemContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  textContainer: {
    flex: 1,
    paddingRight: 10,
  },
  itemTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#000",
  },
  itemSubtitle: {
    fontSize: 12,
    color: "#333",
    marginTop: 2,
  },
  itemLogo: {
    width: 40,
    height: 40,
    resizeMode: "contain",
  },
});

// Main styles for the screen components
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  fixedHeader: {
    backgroundColor: "#002F6C",
    top: 0,
    left: 0,
    right: 0,
    height: 80,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 40,
    paddingHorizontal: 16,
    zIndex: 99,
  },
  logo: {
    width: 90,
    height: 90,
    resizeMode: "contain",
  },
  menu: {
    fontSize: 24,
    color: "#fff",
  },
  headerIcons: {
    flexDirection: "row",
    gap: 10,
  },
  icon: {
    color: "#fff",
    fontSize: 18,
    marginLeft: 15,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
  },
  candidateRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    gap: 0,
  },
  candidateCard: {
  width: 160,           // fixed width for carousel card
  height: 140,          // a bit taller for better spacing
  borderRadius: 10,
  borderWidth: 5,
  borderColor: "#002F6C",
  alignItems: "center",
  justifyContent: "center",
  marginHorizontal: 8,  // space between cards
  paddingTop: 20,
  shadowColor: "#000",
  shadowOpacity: 0.1,
  shadowRadius: 6,
},
  selectedCard: {
    borderWidth: 2,
    borderColor: "#000",
    elevation: 8,
  },
  candidateInfoBox: {
  backgroundColor: "#002F6C",
  paddingVertical: 5,
  borderRadius: 5,
  alignItems: "center",
  justifyContent: "center",
  width: "100%",
  height: "50%",
},
  candidateAvatar: {
  width: 50,       // slightly bigger avatar for better presence
  height: 50,
  borderRadius: 25,
  backgroundColor: "#fff",
  marginBottom: 10,
},
  candidateNameBox: {
  color: "#fff",
  fontSize: 14,
  fontWeight: "bold",
  textAlign: "center",
  paddingVertical: 4,
  flexWrap: "wrap",
},
  partylistBox: {
  color: "#fff",
  fontSize: 12,
  textAlign: "center",
  paddingVertical: 2,
  flexWrap: "wrap",
},
  positionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
  },
  electionCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 24,
    minHeight: 140,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#002F6C",
    marginBottom: 10,
    width: "100%",
    minHeight: 140,
    marginVertical: 10,
    elevation: 6,
  },
  titleContainer: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
  },
  electionTitleTop: {
    fontSize: 16,
    fontWeight: 900,
    textAlign: "left",
    color: "#000",
    paddingTop: 20,
    marginBottom: 10,
  },
  electionTitleBottom: {
    fontSize: 16,
    fontWeight: 400,
    textAlign: "center",
    color: "#000",
    marginBottom: 8,
  },
  electionLogo: {
    width: 80,
    height: 80,
    resizeMode: "contain",
    marginLeft: -80,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    maxHeight: "100%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 5,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  modalScrollView: {
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  closeButton: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#002F6C",
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  closeButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  profileCard: {
    backgroundColor: "#fff",
    alignItems: "center",
    padding: 16,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
    marginBottom: 20,
    marginTop: 20,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 10,
    marginBottom: 15,
    backgroundColor: "#f2f2f2",
  },
  profileInfo: {
    width: "100%",
  },
  label: {
    fontWeight: "bold",
    color: "#333",
  },
  value: {
    marginBottom: 8,
    fontSize: 14,
    color: "#000",
  },
  section: {
    backgroundColor: "#FFD700",
    padding: 16,
    borderRadius: 10,
    marginBottom: 20,
  },
  sectionTitle: {
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 10,
  },
  sectionItem: {
    fontSize: 14,
    marginBottom: 6,
  },
});
