# docker-compose.yml

services:
  server:
    container_name: votex-server
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/votex
    depends_on:
      - mongo

  votex-web:
    container_name: votex-web
    build: ./votex-web
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server

  mongo:
    container_name: votex-mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
