
services:
  mongo_db:
    container_name: voting_sys_mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  backend:
    container_name: voting_sys_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
