# 1. Use Node.js official image lts long term support, smaller image to reduce image size
FROM node:lts-slim 

# 2. Set working directory
WORKDIR /app

# 3. Copy package.json and package-lock.json
COPY package*.json ./

# 4. Install dependencies and PM2 globally
RUN npm install && npm install -g pm2

# 5. Copy the rest of your code
COPY . .

# 6. Expose your app's port
EXPOSE 5000

# 7. Start app with PM2
CMD ["pm2-runtime","src/server.js"]
