# 1. Use Node.js official image
FROM node:lts-slim

# 2. Set working directory
WORKDIR /app

# 3. Copy package.json and package-lock.json
COPY package*.json ./ 


# 4. Install dependencies
RUN npm install

# 5. Install nodemon globally (if needed)
RUN npm install -g nodemon

# 6. Copy the whole project
COPY . .

# 7. Expose the port your app runs on
EXPOSE 5000

# 8. Run in dev mode
CMD ["npm", "run", "dev"]
